---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Должен быть настроен переход с любой страницы сайта на главную страницу по клику на название магазина в шапке сайта
  - Должна быть возможность сбросить фильтры (нужна кнопка "Сбросить")
  - Разграничение доступа (пользователь/администратор) - пользователь не должен иметь возможность удалять товары с сайта или добавлять их
  - Должна быть кнопка возврата наверх страницы
  - Страницы должны быть пронумерованы для удобного перехода на нужную страницу
  - В корзине должна быть возможность изменять количество товара (+/-) и по кнопке "Удалить" такой товар должен удаляться сразу, а не поштучно
